baseURL = "https://seetharamansubramanian.github.io/travelogue"
languageCode = "en-us"
title = "Seetharaman | Travelogue"
theme = "parsa-hugo-personal-blog-theme"
summaryLength = "10"
paginate = 6

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/headroom/headroom.js"
  [[params.plugins.js]]
  URL = "plugins/instafeed/instafeed.min.js"
  [[params.plugins.js]]
  URL = "plugins/masonry/masonry.js"
  [[params.plugins.js]]
  URL = "plugins/reading-time/readingTime.min.js"
  [[params.plugins.js]]
  URL = "plugins/smooth-scroll/smooth-scroll.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  

  
# navigation
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3


[params]
logo = "images/logo.png"
home = "Home"
# hompage layout ( two layout is available,  you can set the another layout by change the value of homeLayoutToggle "true" to "false")
homeLayoutToggle = true
# Meta data
description = "This blog is to catalogue all my travels, and help share them with everyone."
# about author
author = "Seetharaman"
authorImage = "images/banner.jpg"
shortDescription = "I'm a Global Innovation Designer currently completing my Masters at the Royal College of Art in London."
# Contact Form Action
contactFormAction = "https://formspree.io/seetharaman.subrmn@gmail.com"
# Google Analitycs
googleAnalitycsID = "UA-154846500-1"
# copyright
copyright = "a theme by [themefisher.com](themefisher.com)"

  # Preloader
  [params.preloader]
  enable = false
  
  # search
  [params.search]
  enable = true

  # Instagram feed
  [params.instafeed]
  enable = false
  userID = "4044026246"
  accessToken = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"

  # footer
  [params.footer]

    #address
    [[params.footer.addresses]]
    address = "United Kingdom"
    
    [[params.footer.addresses]]
    address = "Notting Hill, London"

    
    #contact information
    [[params.footer.contacts]]
    contactInfo = "Tel: +44 07307708129"
    
    [[params.footer.contacts]]
    contactInfo = "Mail: seetharaman.subrmn@gmail.com"


  # social site
  [[params.social]]
  icon = "ti-facebook"
  URL = "https://www.facebook.com/subramanian.sitaraman.3"
  
  [[params.social]]
  icon = "ti-twitter-alt"
  URL = "https://www.twitter.com/s_seetha_raman"
  
  [[params.social]]
  icon = "ti-linkedin"
  URL = "https://www.linkedin.com/in/seetharaman-subramanian/"
  
  [[params.social]]
  icon = "ti-github"
  URL = "https://github.com/SeetharamanSubramanian"